function out = model
%
% fluid.m
%
% Model exported on Jan 1 2021, 18:05 by COMSOL 5.4.0.225.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('C:\Users\dcy60\Google Drive\Research\MLOPT\code_data\fluid');

model.label('pressure_coursemesh.mph');

model.param.set('width', '2');
model.param.set('height', '0.8');
model.param.set('excess', '0.4');
model.param.set('dx', '0.1');

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 2);

model.result.table.create('tbl1', 'Table');

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').create('r1', 'Rectangle');
model.component('comp1').geom('geom1').feature('r1').set('pos', {'-excess' '0'});
model.component('comp1').geom('geom1').feature('r1').set('size', {'width+excess*2' 'height'});
model.component('comp1').geom('geom1').create('r2', 'Rectangle');
model.component('comp1').geom('geom1').feature('r2').set('pos', {'-excess' '0'});
model.component('comp1').geom('geom1').feature('r2').set('size', {'excess' 'excess'});
model.component('comp1').geom('geom1').create('sq1', 'Square');
model.component('comp1').geom('geom1').feature('sq1').set('pos', {'0' '7*dx'});
model.component('comp1').geom('geom1').feature('sq1').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq2', 'Square');
model.component('comp1').geom('geom1').feature('sq2').set('pos', {'dx' '7*dx'});
model.component('comp1').geom('geom1').feature('sq2').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq3', 'Square');
model.component('comp1').geom('geom1').feature('sq3').set('pos', {'dx*2' '7*dx'});
model.component('comp1').geom('geom1').feature('sq3').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq4', 'Square');
model.component('comp1').geom('geom1').feature('sq4').set('pos', {'dx*3' '7*dx'});
model.component('comp1').geom('geom1').feature('sq4').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq5', 'Square');
model.component('comp1').geom('geom1').feature('sq5').set('pos', {'dx*4' '7*dx'});
model.component('comp1').geom('geom1').feature('sq5').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq6', 'Square');
model.component('comp1').geom('geom1').feature('sq6').set('pos', {'dx*5' '7*dx'});
model.component('comp1').geom('geom1').feature('sq6').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq7', 'Square');
model.component('comp1').geom('geom1').feature('sq7').set('pos', {'dx*6' '7*dx'});
model.component('comp1').geom('geom1').feature('sq7').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq8', 'Square');
model.component('comp1').geom('geom1').feature('sq8').set('pos', {'dx*7' '7*dx'});
model.component('comp1').geom('geom1').feature('sq8').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq9', 'Square');
model.component('comp1').geom('geom1').feature('sq9').set('pos', {'dx*8' '7*dx'});
model.component('comp1').geom('geom1').feature('sq9').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq10', 'Square');
model.component('comp1').geom('geom1').feature('sq10').set('pos', {'dx*9' '7*dx'});
model.component('comp1').geom('geom1').feature('sq10').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq11', 'Square');
model.component('comp1').geom('geom1').feature('sq11').set('pos', {'dx*10' '7*dx'});
model.component('comp1').geom('geom1').feature('sq11').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq12', 'Square');
model.component('comp1').geom('geom1').feature('sq12').set('pos', {'dx*11' '7*dx'});
model.component('comp1').geom('geom1').feature('sq12').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq13', 'Square');
model.component('comp1').geom('geom1').feature('sq13').set('pos', {'dx*12' '7*dx'});
model.component('comp1').geom('geom1').feature('sq13').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq14', 'Square');
model.component('comp1').geom('geom1').feature('sq14').set('pos', {'dx*13' '7*dx'});
model.component('comp1').geom('geom1').feature('sq14').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq15', 'Square');
model.component('comp1').geom('geom1').feature('sq15').set('pos', {'dx*14' '7*dx'});
model.component('comp1').geom('geom1').feature('sq15').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq16', 'Square');
model.component('comp1').geom('geom1').feature('sq16').set('pos', {'dx*15' '7*dx'});
model.component('comp1').geom('geom1').feature('sq16').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq17', 'Square');
model.component('comp1').geom('geom1').feature('sq17').set('pos', {'dx*16' '7*dx'});
model.component('comp1').geom('geom1').feature('sq17').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq18', 'Square');
model.component('comp1').geom('geom1').feature('sq18').set('pos', {'dx*17' '7*dx'});
model.component('comp1').geom('geom1').feature('sq18').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq19', 'Square');
model.component('comp1').geom('geom1').feature('sq19').set('pos', {'dx*18' '7*dx'});
model.component('comp1').geom('geom1').feature('sq19').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq20', 'Square');
model.component('comp1').geom('geom1').feature('sq20').set('pos', {'dx*19' '7*dx'});
model.component('comp1').geom('geom1').feature('sq20').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq21', 'Square');
model.component('comp1').geom('geom1').feature('sq21').set('pos', {'0' '6*dx'});
model.component('comp1').geom('geom1').feature('sq21').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq22', 'Square');
model.component('comp1').geom('geom1').feature('sq22').set('pos', {'dx' '6*dx'});
model.component('comp1').geom('geom1').feature('sq22').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq23', 'Square');
model.component('comp1').geom('geom1').feature('sq23').set('pos', {'dx*2' '6*dx'});
model.component('comp1').geom('geom1').feature('sq23').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq24', 'Square');
model.component('comp1').geom('geom1').feature('sq24').set('pos', {'dx*3' '6*dx'});
model.component('comp1').geom('geom1').feature('sq24').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq25', 'Square');
model.component('comp1').geom('geom1').feature('sq25').set('pos', {'dx*4' '6*dx'});
model.component('comp1').geom('geom1').feature('sq25').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq26', 'Square');
model.component('comp1').geom('geom1').feature('sq26').set('pos', {'dx*5' '6*dx'});
model.component('comp1').geom('geom1').feature('sq26').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq27', 'Square');
model.component('comp1').geom('geom1').feature('sq27').set('pos', {'dx*6' '6*dx'});
model.component('comp1').geom('geom1').feature('sq27').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq28', 'Square');
model.component('comp1').geom('geom1').feature('sq28').set('pos', {'dx*7' '6*dx'});
model.component('comp1').geom('geom1').feature('sq28').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq29', 'Square');
model.component('comp1').geom('geom1').feature('sq29').set('pos', {'dx*8' '6*dx'});
model.component('comp1').geom('geom1').feature('sq29').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq30', 'Square');
model.component('comp1').geom('geom1').feature('sq30').set('pos', {'dx*9' '6*dx'});
model.component('comp1').geom('geom1').feature('sq30').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq31', 'Square');
model.component('comp1').geom('geom1').feature('sq31').set('pos', {'dx*10' '6*dx'});
model.component('comp1').geom('geom1').feature('sq31').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq32', 'Square');
model.component('comp1').geom('geom1').feature('sq32').set('pos', {'dx*11' '6*dx'});
model.component('comp1').geom('geom1').feature('sq32').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq33', 'Square');
model.component('comp1').geom('geom1').feature('sq33').set('pos', {'dx*12' '6*dx'});
model.component('comp1').geom('geom1').feature('sq33').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq34', 'Square');
model.component('comp1').geom('geom1').feature('sq34').set('pos', {'dx*13' '6*dx'});
model.component('comp1').geom('geom1').feature('sq34').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq35', 'Square');
model.component('comp1').geom('geom1').feature('sq35').set('pos', {'dx*14' '6*dx'});
model.component('comp1').geom('geom1').feature('sq35').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq36', 'Square');
model.component('comp1').geom('geom1').feature('sq36').set('pos', {'dx*15' '6*dx'});
model.component('comp1').geom('geom1').feature('sq36').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq37', 'Square');
model.component('comp1').geom('geom1').feature('sq37').set('pos', {'dx*16' '6*dx'});
model.component('comp1').geom('geom1').feature('sq37').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq38', 'Square');
model.component('comp1').geom('geom1').feature('sq38').set('pos', {'dx*17' '6*dx'});
model.component('comp1').geom('geom1').feature('sq38').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq39', 'Square');
model.component('comp1').geom('geom1').feature('sq39').set('pos', {'dx*18' '6*dx'});
model.component('comp1').geom('geom1').feature('sq39').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq40', 'Square');
model.component('comp1').geom('geom1').feature('sq40').set('pos', {'dx*19' '6*dx'});
model.component('comp1').geom('geom1').feature('sq40').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq41', 'Square');
model.component('comp1').geom('geom1').feature('sq41').set('pos', {'0' '5*dx'});
model.component('comp1').geom('geom1').feature('sq41').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq42', 'Square');
model.component('comp1').geom('geom1').feature('sq42').set('pos', {'dx' '5*dx'});
model.component('comp1').geom('geom1').feature('sq42').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq43', 'Square');
model.component('comp1').geom('geom1').feature('sq43').set('pos', {'dx*2' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq43').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq44', 'Square');
model.component('comp1').geom('geom1').feature('sq44').set('pos', {'dx*3' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq44').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq45', 'Square');
model.component('comp1').geom('geom1').feature('sq45').set('pos', {'dx*4' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq45').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq46', 'Square');
model.component('comp1').geom('geom1').feature('sq46').set('pos', {'dx*5' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq46').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq47', 'Square');
model.component('comp1').geom('geom1').feature('sq47').set('pos', {'dx*6' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq47').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq48', 'Square');
model.component('comp1').geom('geom1').feature('sq48').set('pos', {'dx*7' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq48').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq49', 'Square');
model.component('comp1').geom('geom1').feature('sq49').set('pos', {'dx*8' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq49').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq50', 'Square');
model.component('comp1').geom('geom1').feature('sq50').set('pos', {'dx*9' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq50').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq51', 'Square');
model.component('comp1').geom('geom1').feature('sq51').set('pos', {'dx*10' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq51').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq52', 'Square');
model.component('comp1').geom('geom1').feature('sq52').set('pos', {'dx*11' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq52').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq53', 'Square');
model.component('comp1').geom('geom1').feature('sq53').set('pos', {'dx*12' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq53').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq54', 'Square');
model.component('comp1').geom('geom1').feature('sq54').set('pos', {'dx*13' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq54').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq55', 'Square');
model.component('comp1').geom('geom1').feature('sq55').set('pos', {'dx*14' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq55').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq56', 'Square');
model.component('comp1').geom('geom1').feature('sq56').set('pos', {'dx*15' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq56').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq57', 'Square');
model.component('comp1').geom('geom1').feature('sq57').set('pos', {'dx*16' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq57').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq58', 'Square');
model.component('comp1').geom('geom1').feature('sq58').set('pos', {'dx*17' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq58').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq59', 'Square');
model.component('comp1').geom('geom1').feature('sq59').set('pos', {'dx*18' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq59').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq60', 'Square');
model.component('comp1').geom('geom1').feature('sq60').set('pos', {'dx*19' 'dx*5'});
model.component('comp1').geom('geom1').feature('sq60').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq61', 'Square');
model.component('comp1').geom('geom1').feature('sq61').set('pos', {'0' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq61').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq62', 'Square');
model.component('comp1').geom('geom1').feature('sq62').set('pos', {'dx' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq62').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq63', 'Square');
model.component('comp1').geom('geom1').feature('sq63').set('pos', {'dx*2' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq63').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq64', 'Square');
model.component('comp1').geom('geom1').feature('sq64').set('pos', {'dx*3' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq64').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq65', 'Square');
model.component('comp1').geom('geom1').feature('sq65').set('pos', {'dx*4' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq65').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq66', 'Square');
model.component('comp1').geom('geom1').feature('sq66').set('pos', {'dx*5' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq66').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq67', 'Square');
model.component('comp1').geom('geom1').feature('sq67').set('pos', {'dx*6' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq67').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq68', 'Square');
model.component('comp1').geom('geom1').feature('sq68').set('pos', {'dx*7' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq68').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq69', 'Square');
model.component('comp1').geom('geom1').feature('sq69').set('pos', {'dx*8' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq69').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq70', 'Square');
model.component('comp1').geom('geom1').feature('sq70').set('pos', {'dx*9' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq70').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq71', 'Square');
model.component('comp1').geom('geom1').feature('sq71').set('pos', {'dx*10' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq71').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq72', 'Square');
model.component('comp1').geom('geom1').feature('sq72').set('pos', {'dx*11' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq72').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq73', 'Square');
model.component('comp1').geom('geom1').feature('sq73').set('pos', {'dx*12' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq73').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq74', 'Square');
model.component('comp1').geom('geom1').feature('sq74').set('pos', {'dx*13' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq74').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq75', 'Square');
model.component('comp1').geom('geom1').feature('sq75').set('pos', {'dx*14' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq75').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq76', 'Square');
model.component('comp1').geom('geom1').feature('sq76').set('pos', {'dx*15' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq76').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq77', 'Square');
model.component('comp1').geom('geom1').feature('sq77').set('pos', {'dx*16' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq77').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq78', 'Square');
model.component('comp1').geom('geom1').feature('sq78').set('pos', {'dx*17' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq78').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq79', 'Square');
model.component('comp1').geom('geom1').feature('sq79').set('pos', {'dx*18' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq79').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq80', 'Square');
model.component('comp1').geom('geom1').feature('sq80').set('pos', {'dx*19' 'dx*4'});
model.component('comp1').geom('geom1').feature('sq80').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq81', 'Square');
model.component('comp1').geom('geom1').feature('sq81').set('pos', {'0' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq81').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq82', 'Square');
model.component('comp1').geom('geom1').feature('sq82').set('pos', {'dx' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq82').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq83', 'Square');
model.component('comp1').geom('geom1').feature('sq83').set('pos', {'dx*2' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq83').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq84', 'Square');
model.component('comp1').geom('geom1').feature('sq84').set('pos', {'dx*3' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq84').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq85', 'Square');
model.component('comp1').geom('geom1').feature('sq85').set('pos', {'dx*4' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq85').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq86', 'Square');
model.component('comp1').geom('geom1').feature('sq86').set('pos', {'dx*5' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq86').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq87', 'Square');
model.component('comp1').geom('geom1').feature('sq87').set('pos', {'dx*6' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq87').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq88', 'Square');
model.component('comp1').geom('geom1').feature('sq88').set('pos', {'dx*7' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq88').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq89', 'Square');
model.component('comp1').geom('geom1').feature('sq89').set('pos', {'dx*8' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq89').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq90', 'Square');
model.component('comp1').geom('geom1').feature('sq90').set('pos', {'dx*9' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq90').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq91', 'Square');
model.component('comp1').geom('geom1').feature('sq91').set('pos', {'dx*10' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq91').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq92', 'Square');
model.component('comp1').geom('geom1').feature('sq92').set('pos', {'dx*11' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq92').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq93', 'Square');
model.component('comp1').geom('geom1').feature('sq93').set('pos', {'dx*12' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq93').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq94', 'Square');
model.component('comp1').geom('geom1').feature('sq94').set('pos', {'dx*13' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq94').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq95', 'Square');
model.component('comp1').geom('geom1').feature('sq95').set('pos', {'dx*14' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq95').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq96', 'Square');
model.component('comp1').geom('geom1').feature('sq96').set('pos', {'dx*15' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq96').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq97', 'Square');
model.component('comp1').geom('geom1').feature('sq97').set('pos', {'dx*16' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq97').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq98', 'Square');
model.component('comp1').geom('geom1').feature('sq98').set('pos', {'dx*17' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq98').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq99', 'Square');
model.component('comp1').geom('geom1').feature('sq99').set('pos', {'dx*18' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq99').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq100', 'Square');
model.component('comp1').geom('geom1').feature('sq100').set('pos', {'dx*19' 'dx*3'});
model.component('comp1').geom('geom1').feature('sq100').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq101', 'Square');
model.component('comp1').geom('geom1').feature('sq101').set('pos', {'0' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq101').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq102', 'Square');
model.component('comp1').geom('geom1').feature('sq102').set('pos', {'dx' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq102').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq103', 'Square');
model.component('comp1').geom('geom1').feature('sq103').set('pos', {'dx*2' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq103').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq104', 'Square');
model.component('comp1').geom('geom1').feature('sq104').set('pos', {'dx*3' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq104').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq105', 'Square');
model.component('comp1').geom('geom1').feature('sq105').set('pos', {'dx*4' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq105').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq106', 'Square');
model.component('comp1').geom('geom1').feature('sq106').set('pos', {'dx*5' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq106').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq107', 'Square');
model.component('comp1').geom('geom1').feature('sq107').set('pos', {'dx*6' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq107').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq108', 'Square');
model.component('comp1').geom('geom1').feature('sq108').set('pos', {'dx*7' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq108').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq109', 'Square');
model.component('comp1').geom('geom1').feature('sq109').set('pos', {'dx*8' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq109').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq110', 'Square');
model.component('comp1').geom('geom1').feature('sq110').set('pos', {'dx*9' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq110').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq111', 'Square');
model.component('comp1').geom('geom1').feature('sq111').set('pos', {'dx*10' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq111').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq112', 'Square');
model.component('comp1').geom('geom1').feature('sq112').set('pos', {'dx*11' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq112').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq113', 'Square');
model.component('comp1').geom('geom1').feature('sq113').set('pos', {'dx*12' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq113').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq114', 'Square');
model.component('comp1').geom('geom1').feature('sq114').set('pos', {'dx*13' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq114').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq115', 'Square');
model.component('comp1').geom('geom1').feature('sq115').set('pos', {'dx*14' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq115').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq116', 'Square');
model.component('comp1').geom('geom1').feature('sq116').set('pos', {'dx*15' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq116').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq117', 'Square');
model.component('comp1').geom('geom1').feature('sq117').set('pos', {'dx*16' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq117').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq118', 'Square');
model.component('comp1').geom('geom1').feature('sq118').set('pos', {'dx*17' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq118').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq119', 'Square');
model.component('comp1').geom('geom1').feature('sq119').set('pos', {'dx*18' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq119').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq120', 'Square');
model.component('comp1').geom('geom1').feature('sq120').set('pos', {'dx*19' 'dx*2'});
model.component('comp1').geom('geom1').feature('sq120').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq121', 'Square');
model.component('comp1').geom('geom1').feature('sq121').set('pos', {'0' 'dx'});
model.component('comp1').geom('geom1').feature('sq121').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq122', 'Square');
model.component('comp1').geom('geom1').feature('sq122').set('pos', {'dx' 'dx'});
model.component('comp1').geom('geom1').feature('sq122').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq123', 'Square');
model.component('comp1').geom('geom1').feature('sq123').set('pos', {'dx*2' 'dx'});
model.component('comp1').geom('geom1').feature('sq123').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq124', 'Square');
model.component('comp1').geom('geom1').feature('sq124').set('pos', {'dx*3' 'dx'});
model.component('comp1').geom('geom1').feature('sq124').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq125', 'Square');
model.component('comp1').geom('geom1').feature('sq125').set('pos', {'dx*4' 'dx'});
model.component('comp1').geom('geom1').feature('sq125').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq126', 'Square');
model.component('comp1').geom('geom1').feature('sq126').set('pos', {'dx*5' 'dx'});
model.component('comp1').geom('geom1').feature('sq126').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq127', 'Square');
model.component('comp1').geom('geom1').feature('sq127').set('pos', {'dx*6' 'dx'});
model.component('comp1').geom('geom1').feature('sq127').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq128', 'Square');
model.component('comp1').geom('geom1').feature('sq128').set('pos', {'dx*7' 'dx'});
model.component('comp1').geom('geom1').feature('sq128').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq129', 'Square');
model.component('comp1').geom('geom1').feature('sq129').set('pos', {'dx*8' 'dx'});
model.component('comp1').geom('geom1').feature('sq129').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq130', 'Square');
model.component('comp1').geom('geom1').feature('sq130').set('pos', {'dx*9' 'dx'});
model.component('comp1').geom('geom1').feature('sq130').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq131', 'Square');
model.component('comp1').geom('geom1').feature('sq131').set('pos', {'dx*10' 'dx'});
model.component('comp1').geom('geom1').feature('sq131').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq132', 'Square');
model.component('comp1').geom('geom1').feature('sq132').set('pos', {'dx*11' 'dx'});
model.component('comp1').geom('geom1').feature('sq132').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq133', 'Square');
model.component('comp1').geom('geom1').feature('sq133').set('pos', {'dx*12' 'dx'});
model.component('comp1').geom('geom1').feature('sq133').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq134', 'Square');
model.component('comp1').geom('geom1').feature('sq134').set('pos', {'dx*13' 'dx'});
model.component('comp1').geom('geom1').feature('sq134').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq135', 'Square');
model.component('comp1').geom('geom1').feature('sq135').set('pos', {'dx*14' 'dx'});
model.component('comp1').geom('geom1').feature('sq135').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq136', 'Square');
model.component('comp1').geom('geom1').feature('sq136').set('pos', {'dx*15' 'dx'});
model.component('comp1').geom('geom1').feature('sq136').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq137', 'Square');
model.component('comp1').geom('geom1').feature('sq137').set('pos', {'dx*16' 'dx'});
model.component('comp1').geom('geom1').feature('sq137').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq138', 'Square');
model.component('comp1').geom('geom1').feature('sq138').set('pos', {'dx*17' 'dx'});
model.component('comp1').geom('geom1').feature('sq138').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq139', 'Square');
model.component('comp1').geom('geom1').feature('sq139').set('pos', {'dx*18' 'dx'});
model.component('comp1').geom('geom1').feature('sq139').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq140', 'Square');
model.component('comp1').geom('geom1').feature('sq140').set('pos', {'dx*19' 'dx'});
model.component('comp1').geom('geom1').feature('sq140').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq141', 'Square');
model.component('comp1').geom('geom1').feature('sq141').set('pos', [0 0]);
model.component('comp1').geom('geom1').feature('sq141').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq142', 'Square');
model.component('comp1').geom('geom1').feature('sq142').set('pos', {'dx' '0'});
model.component('comp1').geom('geom1').feature('sq142').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq143', 'Square');
model.component('comp1').geom('geom1').feature('sq143').set('pos', {'dx*2' '0'});
model.component('comp1').geom('geom1').feature('sq143').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq144', 'Square');
model.component('comp1').geom('geom1').feature('sq144').set('pos', {'dx*3' '0'});
model.component('comp1').geom('geom1').feature('sq144').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq145', 'Square');
model.component('comp1').geom('geom1').feature('sq145').set('pos', {'dx*4' '0'});
model.component('comp1').geom('geom1').feature('sq145').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq146', 'Square');
model.component('comp1').geom('geom1').feature('sq146').set('pos', {'dx*5' '0'});
model.component('comp1').geom('geom1').feature('sq146').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq147', 'Square');
model.component('comp1').geom('geom1').feature('sq147').set('pos', {'dx*6' '0'});
model.component('comp1').geom('geom1').feature('sq147').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq148', 'Square');
model.component('comp1').geom('geom1').feature('sq148').set('pos', {'dx*7' '0'});
model.component('comp1').geom('geom1').feature('sq148').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq149', 'Square');
model.component('comp1').geom('geom1').feature('sq149').set('pos', {'dx*8' '0'});
model.component('comp1').geom('geom1').feature('sq149').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq150', 'Square');
model.component('comp1').geom('geom1').feature('sq150').set('pos', {'dx*9' '0'});
model.component('comp1').geom('geom1').feature('sq150').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq151', 'Square');
model.component('comp1').geom('geom1').feature('sq151').set('pos', {'dx*10' '0'});
model.component('comp1').geom('geom1').feature('sq151').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq152', 'Square');
model.component('comp1').geom('geom1').feature('sq152').set('pos', {'dx*11' '0'});
model.component('comp1').geom('geom1').feature('sq152').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq153', 'Square');
model.component('comp1').geom('geom1').feature('sq153').set('pos', {'dx*12' '0'});
model.component('comp1').geom('geom1').feature('sq153').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq154', 'Square');
model.component('comp1').geom('geom1').feature('sq154').set('pos', {'dx*13' '0'});
model.component('comp1').geom('geom1').feature('sq154').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq155', 'Square');
model.component('comp1').geom('geom1').feature('sq155').set('pos', {'dx*14' '0'});
model.component('comp1').geom('geom1').feature('sq155').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq156', 'Square');
model.component('comp1').geom('geom1').feature('sq156').set('pos', {'dx*15' '0'});
model.component('comp1').geom('geom1').feature('sq156').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq157', 'Square');
model.component('comp1').geom('geom1').feature('sq157').set('pos', {'dx*16' '0'});
model.component('comp1').geom('geom1').feature('sq157').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq158', 'Square');
model.component('comp1').geom('geom1').feature('sq158').set('pos', {'dx*17' '0'});
model.component('comp1').geom('geom1').feature('sq158').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq159', 'Square');
model.component('comp1').geom('geom1').feature('sq159').set('pos', {'dx*18' '0'});
model.component('comp1').geom('geom1').feature('sq159').set('size', 'dx');
model.component('comp1').geom('geom1').create('sq160', 'Square');
model.component('comp1').geom('geom1').feature('sq160').set('pos', {'dx*19' '0'});
model.component('comp1').geom('geom1').feature('sq160').set('size', 'dx');
model.component('comp1').geom('geom1').create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('dif1').set('intbnd', false);
model.component('comp1').geom('geom1').feature('dif1').selection('input').set({'r1'});
model.component('comp1').geom('geom1').feature('dif1').selection('input2').set({'r2' 'sq1' 'sq2' 'sq3' 'sq4'});
model.component('comp1').geom('geom1').run;

model.component('comp1').material.create('mat1', 'Common');

model.component('comp1').physics.create('spf', 'LaminarFlow', 'geom1');
model.component('comp1').physics('spf').create('inl1', 'InletBoundary', 1);
model.component('comp1').physics('spf').feature('inl1').selection.set([1]);
model.component('comp1').physics('spf').create('out1', 'OutletBoundary', 1);
model.component('comp1').physics('spf').feature('out1').selection.set([347]);

model.component('comp1').mesh('mesh1').create('map1', 'Map');
model.component('comp1').mesh('mesh1').feature('map1').create('size1', 'Size');

model.result.table('tbl1').comments('Line Average 1 (p)');

model.component('comp1').view('view1').axis.set('xmin', -0.6024884581565857);
model.component('comp1').view('view1').axis.set('xmax', 2.969104290008545);
model.component('comp1').view('view1').axis.set('ymin', -0.9674765467643738);
model.component('comp1').view('view1').axis.set('ymax', 1.6224944591522217);

model.component('comp1').material('mat1').propertyGroup('def').set('density', '1');
model.component('comp1').material('mat1').propertyGroup('def').set('dynamicviscosity', '1e-2');

model.component('comp1').physics('spf').prop('ShapeProperty').set('order_fluid', 5);
model.component('comp1').physics('spf').feature('inl1').set('ComponentWise', 'VelocityFieldComponentWise');
model.component('comp1').physics('spf').feature('inl1').set('U0in', 0.01);
model.component('comp1').physics('spf').feature('inl1').set('u0', [1; 0; 0]);

model.component('comp1').mesh('mesh1').feature('size').set('hauto', 7);
model.component('comp1').mesh('mesh1').feature('size').set('table', 'cfd');
model.component('comp1').mesh('mesh1').feature('map1').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('map1').feature('size1').set('hmax', 0.1);
model.component('comp1').mesh('mesh1').feature('map1').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('map1').feature('size1').set('hmin', 0.1);
model.component('comp1').mesh('mesh1').feature('map1').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').run;

model.study.create('std1');
model.study('std1').create('stat', 'Stationary');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature.remove('fcDef');

model.result.numerical.create('av1', 'AvLine');
model.result.numerical('av1').selection.set([1]);
model.result.numerical('av1').set('probetag', 'none');
model.result.create('pg1', 'PlotGroup2D');
model.result.create('pg2', 'PlotGroup2D');
model.result('pg1').create('surf1', 'Surface');
model.result('pg2').create('con1', 'Contour');

model.sol('sol1').attach('std1');
model.sol('sol1').feature('s1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('s1').feature('fc1').set('initstep', 0.01);
model.sol('sol1').feature('s1').feature('fc1').set('minstep', 1.0E-6);
model.sol('sol1').feature('s1').feature('fc1').set('maxiter', 100);
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').runAll;

model.result.numerical('av1').set('table', 'tbl1');
model.result.numerical('av1').set('expr', {'p'});
model.result.numerical('av1').set('unit', {'Pa'});
model.result.numerical('av1').set('descr', {'Pressure'});
model.result.numerical('av1').setResult;
model.result('pg1').label('Velocity (spf)');
model.result('pg1').set('frametype', 'spatial');
model.result('pg1').feature('surf1').label('Surface');
model.result('pg1').feature('surf1').set('smooth', 'internal');
model.result('pg1').feature('surf1').set('resolution', 'normal');
model.result('pg2').label('Pressure (spf)');
model.result('pg2').set('frametype', 'spatial');
model.result('pg2').feature('con1').label('Contour');
model.result('pg2').feature('con1').set('expr', 'p');
model.result('pg2').feature('con1').set('unit', 'Pa');
model.result('pg2').feature('con1').set('descr', 'Pressure');
model.result('pg2').feature('con1').set('number', 40);
model.result('pg2').feature('con1').set('smooth', 'internal');
model.result('pg2').feature('con1').set('resolution', 'normal');

model.label('fluid.mph');

out = model;
